service: aws-example
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    DYNAMODB_TABLE: ${self:service}-sentence-${sls:stage}
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'dynamodb:PutItem'
            - 'dynamodb:Get*'
            - 'dynamodb:Scan*'
            - 'dynamodb:UpdateItem'
            - 'dynamodb:DeleteItem'
          Resource: arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:service}-sentence-${sls:stage}

functions:
  buildSentence:
    handler: handler.buildSentence
    events:
     - http:
         path: sentence
         method: get

  updateSentence:
    handler: handler.updateSentence
    events:
     - http:
         path: sentence
         method: post


resources:
  Resources:
    SentenceTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: primary_key
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: primary_key
            KeyType: HASH
        TableName: ${self:service}-sentence-${sls:stage}
